import type { University } from "./types";

export const UNIVERSITIES: University[] = [
  {
    id: "1",
    slug: "mit",
    name: "Massachusetts Institute of Technology",
    country: "United States",
    region: "North America",
    rank: 1,
    trustScore: 92,
    lastUpdated: "2025-11-18 05:25:43+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "2",
    slug: "stanford",
    name: "Stanford University",
    country: "United States",
    region: "North America",
    rank: 2,
    trustScore: 90,
    lastUpdated: "2025-11-18 05:24:45+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "3",
    slug: "oxford",
    name: "University of Oxford",
    country: "United Kingdom",
    region: "Europe",
    rank: 3,
    trustScore: 88,
    lastUpdated: "2025-11-18 05:24:24+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "4",
    slug: "nus",
    name: "National University of Singapore",
    country: "Singapore",
    region: "Asia",
    rank: 4,
    trustScore: 85,
    lastUpdated: "2025-11-18 05:24:59+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "5",
    slug: "melbourne",
    name: "University of Melbourne",
    country: "Australia",
    region: "Oceania",
    rank: 5,
    trustScore: 83,
    lastUpdated: "2025-11-18 05:22:32+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "6",
    slug: "tokyo",
    name: "The University of Tokyo",
    country: "Japan",
    region: "Asia",
    rank: 6,
    trustScore: 82,
    lastUpdated: "2025-11-18 05:23:09+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "7",
    slug: "toronto",
    name: "University of Toronto",
    country: "Canada",
    region: "North America",
    rank: 7,
    trustScore: 81,
    lastUpdated: "2025-11-18 05:24:06+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "8",
    slug: "eth-zurich",
    name: "ETH Zurich",
    country: "Switzerland",
    region: "Europe",
    rank: 8,
    trustScore: 80,
    lastUpdated: "2025-11-18 05:26:01+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "9",
    slug: "kth",
    name: "KTH Royal Institute of Technology",
    country: "Sweden",
    region: "Europe",
    rank: 9,
    trustScore: 78,
    lastUpdated: "2025-11-18 05:23:15+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
  {
    id: "10",
    slug: "ui",
    name: "Universitas Indonesia",
    country: "Indonesia",
    region: "Asia",
    rank: 10,
    trustScore: 74,
    lastUpdated: "2025-11-18 05:25:12+00",
    metrics: {
      collaboration: null,
      privacy: null,
      accountability: null,
      security: null,
      ethicsInAI: null,
      fairness: null,
      transparency: null,
      continuousLearning: null,
    },
  },
];

export const REGIONS = Array.from(new Set(UNIVERSITIES.map((u) => u.region))).sort();
export const COUNTRIES = Array.from(new Set(UNIVERSITIES.map((u) => u.country))).sort();

import { Submission, User } from "./types";

export const mockSubmissions: Submission[] = [
  { id: "sub1", name: "Universitas Gadjah Mada" },
  { id: "sub2", name: "Institut Teknologi Bandung" },
  { id: "sub3", name: "Universitas Sebelas Maret" },
];

export const mockUsers: User[] = [
  { id: "user1", name: "John Doe", email: "john@example.com", role: "user" },
  { id: "user2", name: "Jane Smith", email: "jane@example.com", role: "university" },
  { id: "user3", name: "Admin User", email: "admin@example.com", role: "admin" },
];
